### ISSUE TITLE
Incompatible MSVC runtime lib causes crashes on certain systems

### ISSUE THREAD

**Issue by mos9527** [K0lb3/astc-encoder-py#6]
As discussed in https://github.com/K0lb3/astc-encoder-py/pull/2 a certain issue in MSVC's STL implementation caused crashes when using `std::mutex` built with VC2022 headers on a VC2019 runtime.
The initial fix was [to use compiler flag `_DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR`](https://github.com/K0lb3/astc-encoder-py/pull/2/commits/5cce309d200f66f770a54856ad544308ef702a4e) which was then superseded by https://github.com/K0lb3/astc-encoder-py/pull/3, bundling the necessary runtime with `delvewheel` instead.
However, the fix seems to have been removed in https://github.com/K0lb3/astc-encoder-py/commit/e2ee9bce0d7741dda131072d05422c122dd3a1f5 (0.1.10), which causes the issue (again):
- https://github.com/mos9527/sssekai_blender_io/issues/13

Is it possible to reintroduce one of the fixes in a later version? Or is it advisable to stick with `0.1.9` for the time being?

**Comment by K0lb3** [comment]
Sorry, I forgot to include the fix you want.

I investigated the issue a bit more, and noticed that Python bundles its own suiting runtime, and that it's not recommended to include the runtime within wheels.

**Comment by mos9527** [comment]
> Sorry, I forgot to include the fix you want.
> 
> I investigated the issue a bit more, and noticed that Python bundles its own suiting runtime, and that it's not recommended to include the runtime within wheels.

I've come across [a StackOverflow post](https://stackoverflow.com/a/19944935) about it as well. And for most cases (e.g. with offical builds of newer Python redists) where this isn't a issue this does seem unnecessary if not potentially harmful.

[Would adding the compiler flag](https://github.com/K0lb3/astc-encoder-py/pull/2/commits/5cce309d200f66f770a54856ad544308ef702a4e) cause issues though? This does allow the extension to run on some of the more peculiar Python redists (e.g. Blender's in-built Python runtime which still bundles VC2019 runtime even with their latest 4.3 release (bundling Python 3.11) for some reason).

**Comment by K0lb3** [comment]
Last week I pushed a new version with the flag you found instead of including the msvrt, so it should be fine now.
I agree that it would be best to make the flag optonal, so that it only gets used if needed, so in a cibuilswheel environment and on user demand.

**Comment by mos9527** [comment]
Ah, sorry for not noticng that eariler. Tests with Blender Windows builds now works on my end. Tysm for the fix!
I'll be closing the issue for now.
